### ISSUE TITLE
Alguma implementação para: BuyPage Loja ?

### ISSUE THREAD

**Issue by ricardojlrufino** [mmaico/cielo-module#1]
Amigo, essa api pode ser usada para o modo: BuyPage Loja ?
Você conhece alguma solução ?

**Comment by mmaico** [comment]
Olá Ricardo,

Sim, você poderar usar mesmo com o BuyPage. Dentro de CieloPayment existe um objeto chamado CieloCard nesse objeto que deverá ser enviado os dados do cartão do cliente.

Qualquer dúvida me avise.

**Comment by ricardojlrufino** [comment]
Olhando por cima da documentação, vi que o formado do XML era em português, ele aceita em inglês também... ?

**Comment by mmaico** [comment]
Não aceita, somente português. Nessa api eu criei um template(xml) onde mando um objeto para renderizar dentro do modelo deles.

**Comment by ricardojlrufino** [comment]
Ahh ta certo, tava procurando isso mas n tinha achado.. valeu aew pelas
dicas.

Atenciosamente,

## Ricardo JL Rufino

CriativaSoft http://www.criativasoft.com.br - _Desenvolvimento de
Sistemas com Qualidade
Analista e Engenheiro de Software_
_Skype_: ricardojlrufino
_Linkedin_: br.linkedin.com/pub/ricardo-rufino/5a/696/81aricardo.jl.rufino@gmail.com

2013/8/1 Marcelo Maico notifications@github.com

**Comment by ricardojlrufino** [comment]
hh ta certo, tava procurando isso mas n tinha achado.. valeu aew pelas dicas.
