### ISSUE TITLE
Estabilidade do projeto

### ISSUE THREAD

**Issue by edpichler** [mmaico/cielo-module#2]
Olá, estou pensando usar sua biblioteca. Ela está estável para uso em produção? Tem sites usando?

Obrigado

**Comment by mmaico** [comment]
Olá, sim ela está estável e já estou usando a bastante tempo. Se tiver algum problema eu posso te ajudar porem, o códito está bem coberto de testes e está fácil de acrecentar funcionalidades.

abraço!

**Comment by edpichler** [comment]
Legal @mmaico, vou usá-la então e, caso precisar e puder, enviarei uns pull requests para contribuir com seu projeto =]

**Comment by mmaico** [comment]
Show!! Obrigado por colaborar ;)
