### ISSUE TITLE
Somente Buy Page?

### ISSUE THREAD

**Issue by edpichler** [mmaico/cielo-module#4]
Olá, uma dúvida. Esse módulo é somente versão do pagamento BuyPage, ou seja, o usuário vai pagar no site da Cielo? Não tem os outros métodos da API implementados?

**Comment by mmaico** [comment]
Olá edpichler, funciona também no modo onde você envia no numero do cartão. Quando criei minha necessidade era somente o BuyPage então coloquei os exemplos correlatos, porem a diferença de um modo para o outro é a quantidade de parametros que você passa.

Para funcionar passando o cartão é só popular o objeto  CieloCard, depois só setar no CieloPayment:
CieloCard cieloCard = new CieloCard();
//Popular objeto

CieloPayment cieloPayment = CieloPayment.build().withCreditCardType(CieloCreditCardType.VISA)
            .withPlots(3)
            .withModality(CieloModality.INSTALLMENTS_BUSINESS_STABLISHMENT);

 //Setando  o cartao no cieloPayment
 cieloPayment.setCard(card);

Qualquer dúvida só falar.

obs: vou colocar um withCreditCard no builder para facilitar a montagem do CieloPayment com um CieloCard.

**Comment by mmaico** [comment]
Já atualizei. Agora só adicionar o cartão no builder 
  CieloCard cieloCard = new CieloCard();

  CieloPayment cieloPayment = CieloPayment.build().withCreditCardType(CieloCreditCardType.VISA)
      .withPlots(3)
      .withCieloCard(cieloCard)
     .withModality(CieloModality.INSTALLMENTS_BUSINESS_STABLISHMENT);

obs: Obrigado pelo pull request da documentacao.

**Comment by edpichler** [comment]
@mmaico Bom dia.
Você atualizou a documentação mas o CieloCard já existia quando postei a pergunta? E o template XML já estava pronto ou preciso pegar sua atualização para funcionar?
